name: Build and Test

on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

jobs:
  testing:
    name: Linux focal ${{ matrix.configuration }} test build
    container:
      image: swift:focal
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: [debug] #, release
    steps:
    - uses: actions/checkout@v2
    - name: Install libsqlite3
      run: apt-get update && apt-get install -y --no-install-recommends libsqlite3-dev
    - uses: actions/cache@v2
      with:
        path: .build
        key: ${{ runner.os }}-focal-spm-cache-${{ hashFiles('Package.resolved') }}
    
    - name: Check Swift version
      run: swift --version
    
    # create docker image
    # push to DockerHub
    # use vpn to get onto TUM network
    # ssh into the RPi
    # upload any updated image
    # 
  
    # - name: Build
    #   if: matrix.configuration == 'release'
    #   run: swift build --configuration ${{ matrix.configuration }}

    - name: Build & Test
      if: matrix.configuration == 'debug'
      run: swift test --configuration ${{ matrix.configuration }} --enable-test-discovery


  push_to_registry:
    name: Push Docker image to GitHub Packages

    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: jass-2021/smart-infrastructure/webservice
          tag_with_ref: true 