name: Build and Test

on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

jobs:
  linux:
    name: Linux focal ${{ matrix.configuration }} test build
    container:
      image: swift:focal
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: [debug, release]
    steps:
    - uses: actions/checkout@v2
    - name: Install libsqlite3
      run: apt-get update && apt-get install -y --no-install-recommends libsqlite3-dev
    - uses: actions/cache@v2
      with:
        path: .build
        key: ${{ runner.os }}-focal-spm-cache-${{ hashFiles('Package.resolved') }}
    - name: Check Swift version
      run: swift --version
    - name: Build
      if: matrix.configuration == 'release'
      run: swift build --configuration ${{ matrix.configuration }}
    - name: Build & Test
      if: matrix.configuration == 'debug'
      run: swift test --configuration ${{ matrix.configuration }} --enable-test-discovery
