# build-and-test
# Date started: 30th March 2021
# Date of last update: 31st March 2021

# Purpose:
# Attempts to deploy smart-infrastructure codebase to TUM's Duckie-Town LIFX
# bulbs on push/pull-request to trunk

# By: Ameena Hassan and Julian Christl

# Shout outs to:
# Paul Schmiedmayer
# Hialus && He Xiaoning

# Developed also by discussions with:
# Timor Morrien
# Ivan Procaccini

# Related documentation can be found at:
# - https://docs.docker.com/engine/reference/commandline/images/
# - https://www.nginx.com/resources/wiki/start/topics/tutorials/commandline/

#
# >> Ping Ameena if we forgot you!
#

name: Build and Test # We should make this more accurate, but later on.


# Specifically mentions when to trigger the pipeline #
on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

# Used to store global variables, adapt as necessary. #
env:
  # The name of our Docker image to deploy
  IMAGE_NAME: jass-smart-infrastructure-webservice

# Jobs the pipeline is supposed to run #
jobs:

    # Job # 5: #     ## DEPLOY ##
  deploy_to_raspberry:
    # Only executed once Docker image is successfully built and pushed to registry #


    # Move Docker image from Registry to RPi #
    name: Deploy Docker image to the Raspberry

    runs-on: ubuntu-latest

    # if head is not at trunk, fail before running the steps! #
    if: github.ref == 'refs/heads/trunk'

    steps:

      # Perform deployment via SSH
      - name: Deploy with SSH
        uses: fifsky/ssh-action@v0.0.5
        with:
          # Command to execute on the remote server, i.e. another mess
          command: |
            echo ${{ env.IMAGE_NAME }}

          # IP address of the MWN server
          host: 131.159.38.52

          # Username for authentication
          user: ubuntu

          # Port number of the server
          port: 10010

          # String that contains a private key, stored on JASS-2021 secrets (OpenSSH format)
          key: ${{ secrets.TUM_RBP_1_SECRET }}

