name: Swift

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
  

  docker:
  
    runs-on: macos-latest
  
    steps:
    - uses: actions/checkout@v2
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v1.1.1
    - name: Build and push Docker images
      uses: docker/build-push-action@v2.3.0
      with:
        file: .devcontainer/Dockerfile
    


